### ISSUE TITLE
Die Farbe der Columns wird nicht angepasst.

### ISSUE THREAD

**Issue by ChristophTank** [squirreltech/chartr#1]
![bildschirmfoto 2015-09-16 um 15 55 08](https://cloud.githubusercontent.com/assets/13638915/9929720/ef8fd448-5d2e-11e5-8909-b460429930a2.png)

**Comment by rexblack** [comment]
Fixed by ed914f6

**Comment by rexblack** [comment]
Implementation is not correct

**Comment by ChristophTank** [comment]
https://drive.google.com/open?id=0Bw8sOxa_pr_cXzV3dW5fVlROMms
